### ISSUE TITLE
Token parsing doesn't accommodate for values that include `:`

### ISSUE THREAD

**Issue by mistermoe** [fergiemcdowall/fergies-inverted-index#40]
@fergiemcdowall I wanted to start by thanking you for writing [search-index](https://github.com/fergiemcdowall/search-index). It's great.

## Context
While using `search-index`, i realized that i couldn't query for values that had `:` in them. I traced down the source of the problem and realized that token parsing is actually happening in this library. Specifically [here](https://github.com/fergiemcdowall/fergies-inverted-index/blob/master/src/parseToken.js#L20-L23)

## Reproduction
```javascript
import si from 'search-index';

const index = await si({ name: 'INDEX' });

await index.PUT([{ author: 'did:ex:alice' }], {
  tokenSplitRegex: /[\p{L}\d:]+/gu
})

const result = await index.QUERY({ AND: ['author:did:123:456'] });
console.log(result);
```
Output:
```
{ RESULT: [], RESULT_LENGTH: 0 }
```

**Comment by fergiemcdowall** [comment]
Thanks for the issue and PR @mistermoe . I am on holiday and paternity leave at the moment, so its taking me a bit longer than usual to respond.

This all seems very reasonable, and I will merge ASAP

**Comment by mistermoe** [comment]
Thanks for taking the time to get this merged in during leave 😃
