### ISSUE TITLE
Replacement for PouchDB needs?

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/fergies-inverted-index#6]
Making a search engine in the browser, I see that I have some needs for storing different things. Earlier I've looked into PouchDB. Could I use Fergie's inverted index for some regular key-value storing? It would mean one less dependency.

**Comment by fergiemcdowall** [comment]
fergies-inverted-index (need to find a better name!) is good for when you are putting a lot of objects into an index, and you want them to be retrievable by their properties. A good example would be a classifieds application where each ad is an object with various properties that a user might want to search for- price, various categories, title, location, etc.

If you just have a list of key:value pairs then something like levelup or vanilla indexeddb would be a better choice.

**Comment by eklem** [comment]
Ok, thanks =)

**Comment by eklem** [comment]
Hmmm... Actually, it may be nice to have objects and then properties like `indexed:true/false`, `indexed-date:` etc, and then retrieve by `indexed:fales`. So we'll see =)
